"""Deterministic TypeScript client generated from the architect's frozen contract."""

import json
import re


def ts_type(schema):
    if not schema:
        return "unknown"
    if "$ref" in schema:
        raise ValueError("Contract must inline JSON schemas; references are unsupported")
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema or "oneOf" in schema:
        return " | ".join(ts_type(s) for s in schema.get("anyOf", schema.get("oneOf", [])))
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_type({**schema, "type": value}) for value in kind)
    if kind == "object":
        required = schema.get("required", [])
        fields = [
            f"{json.dumps(key)}{'' if key in required else '?'}: {ts_type(value)}"
            for key, value in schema.get("properties", {}).items()
        ]
        return "{ " + "; ".join(fields) + " }" if fields else "Record<string, unknown>"
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def render_client(contract):
    definitions = []
    routes = {}
    for endpoint in contract["endpoints"]:
        key = endpoint["method"] + " " + endpoint["path"]
        params = re.findall(r"\{([A-Za-z_][A-Za-z0-9_]*)\}", endpoint["path"])
        param_type = "{ " + "; ".join(f"{json.dumps(p)}: string | number" for p in params) + " }"
        options = []
        if params:
            options.append("params: " + param_type)
        if endpoint["request_schema"] is not None:
            options.append("body: " + ts_type(endpoint["request_schema"]))
        options.append("signal?: AbortSignal")
        definitions.append(
            f"  {json.dumps(key)}: {{ options: {{ {'; '.join(options)} }}; "
            f"response: {ts_type(endpoint['response_schema'])} }}"
        )
        routes[key] = {
            "method": endpoint["method"],
            "path": endpoint["path"],
            "status": endpoint["success_status"],
        }
    return (
        "// Generated by the company. Do not edit; change the approved contract instead.\n"
        "type Operations = {\n" + ";\n".join(definitions) + "\n};\n"
        "const routes: Record<string, {method: string; path: string; status: number}> = "
        + json.dumps(routes)
        + ";\n"
        "export async function api<K extends keyof Operations>(\n"
        "  operation: K, options: Operations[K]['options']\n"
        "): Promise<Operations[K]['response']> {\n"
        "  const route = routes[operation];\n"
        "  const input = options as { params?: Record<string, string | number>; body?: unknown; signal?: AbortSignal };\n"
        "  const path = route.path.replace(/\\{([^}]+)\\}/g, (_, key: string) => {\n"
        "    const value = input.params?.[key];\n"
        "    if (value === undefined) throw new Error('Missing path parameter: ' + key);\n"
        "    return encodeURIComponent(String(value));\n"
        "  });\n"
        "  const base = (process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000').replace(/\\/$/, '');\n"
        "  const response = await fetch(base + path, { method: route.method,\n"
        "    credentials: 'include', signal: input.signal,\n"
        "    headers: input.body === undefined ? undefined : {'Content-Type': 'application/json'},\n"
        "    body: input.body === undefined ? undefined : JSON.stringify(input.body) });\n"
        "  if (response.status !== route.status) throw new Error('API request failed: ' + response.status);\n"
        "  if (route.status === 204) return undefined as Operations[K]['response'];\n"
        "  return await response.json() as Operations[K]['response'];\n"
        "}\n"
    )
